 This assignment will not be graded and is only for practice.

Split the dataset into train dataset and test dataset in the following manner :
- data (rows) index [0, 8271] should be the train dataset
- data (rows) index from 8272 till last row should be the test dataset
- columns except of the label(Sale Price) vector should be the feature matrix (X_train or X_test)
- make label vector (Y_train or y_test) containing values only from the target feature.

[Click here to View the Dataset](https://drive.google.com/file/d/1fZMUEsgfLvCPKWnTOEoJd8Xnn_MOumMM/view?usp=sharing)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mlp-oppe1-mock-2/Model_Building_1.csv

In [2]:
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import PolynomialFeatures
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso, SGDRegressor, RidgeCV

### Q1: Which dataset are you using for this Module 2?

- [x] Model_Building_1
- [ ] Model_Building_2
- [ ] Model_Building_3
- [ ] Model_Building_4
- [ ] Model_Building_5

In [3]:
data = pd.read_csv("/kaggle/input/mlp-oppe1-mock-2/Model_Building_1.csv")
data.head()

,Locality_Bridgeport,Locality_Fairfield,Locality_Greenwich,Locality_Norwalk,Locality_Stamford,Locality_Waterbury,Locality_West Hartford,Property_Four Family,Property_Single Family,Property_Three Family,...,Face_North,Face_South,Face_West,Year,Estimated Value,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Sale Price
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.013548,0.0,0.142857,0.060316,0.013981,5187000.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.013548,0.0,0.142857,0.072283,0.013981,480000.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.003405,0.0,0.142857,0.020584,0.013981,152000.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.002618,0.0,0.142857,0.095261,0.013981,60000.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.005356,0.2,0.142857,0.149832,0.013981,250000.0

In [4]:
X = data.drop(columns="Sale Price")
y = data["Sale Price"]

X.head()

,Locality_Bridgeport,Locality_Fairfield,Locality_Greenwich,Locality_Norwalk,Locality_Stamford,Locality_Waterbury,Locality_West Hartford,Property_Four Family,Property_Single Family,Property_Three Family,...,Face_East,Face_North,Face_South,Face_West,Year,Estimated Value,num_rooms,num_bathrooms,carpet_area,property_tax_rate
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.013548,0.0,0.142857,0.060316,0.013981
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.013548,0.0,0.142857,0.072283,0.013981
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.003405,0.0,0.142857,0.020584,0.013981
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.002618,0.0,0.142857,0.095261,0.013981
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.005356,0.2,0.142857,0.149832,0.013981

In [5]:
X.shape

(10000, 25)

In [6]:
X_train = X.iloc[:8271]
X_test = X.iloc[8272:]

y_train = y.iloc[:8271]
y_test = y.iloc[8272:]

X_train.shape, X_test.shape

((8271, 25), (1728, 25))

### Q2: Apply LinearRegression on the train dataset(X_train and y_train). What is the R2 score on the test dataset(X_test and y_test). ( Upto 4 digits after decimal points)

In [7]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [8]:
round(model.score(X_test, y_test), 4)

0.648

### Q3: Enter the maximum value of 𝑅2 score you got using the LinearRegression model when computed with 5 folds from the training dataset (X_train and y_train) using cross_val_score. ( Upto 4 digits after decimal points) obtained.

In [9]:
cv = cross_val_score(LinearRegression(), X_train, y_train, scoring="r2", cv=5)
cv

array([0.6349542 , 0.76526846, 0.74054327, 0.81364981, 0.65613727])

In [10]:
round(cv.max(), 4)

0.8136

### Q4: Train Ridge and Lasso with random_state=27 and keep other parameters as default using train dataset. Which one has the least "mean squared error" for the test dataset.
- [x] Ridge
- [ ] Lasso
- [ ] Both are Equal

In [11]:
ridge_model = Ridge(random_state=27)
lasso_model = Lasso(random_state=27)

ridge_model.fit(X_train, y_train)
lasso_model.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.077e+14, tolerance: 1.091e+12
  model = cd_fast.enet_coordinate_descent(

Lasso(random_state=27)

In [12]:
y_ridge_preds = ridge_model.predict(X_test)
y_lasso_preds = lasso_model.predict(X_test)

ridge_mse = mean_squared_error(y_test, y_ridge_preds)
lasso_mse = mean_squared_error(y_test, y_lasso_preds)

mse_scores = pd.Series([ridge_mse, lasso_mse])
mse_scores.min(), mse_scores.argmin()

(301999858948.32825, 0)

Train the SGDRegressor(random_state=27,warm_start=True) with maximum passes over the train dataset can be 100.

### Q5: Write the correct R2 score for this estimator on test dataset [NAT] (correct Upto 4 digits)

In [13]:
sgd_model = SGDRegressor(random_state=27, warm_start=True, max_iter=100)
sgd_model.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:1548: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDRegressor(max_iter=100, random_state=27, warm_start=True)

In [14]:
round(sgd_model.score(X_test, y_test), 4)

0.5266

(Common Instructions for Question 14 and 15)

create a pipeline of the `PolynomialFeatures(interaction_only=True)` as transformer and Lasso as an estimator.

Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.

- Keep polynomial degree as : `[1,2]`
- lasso alpha value to be taken as : `[10,100,1000,10000]`
- scoring : `neg_mean_absolute_error`.
- cv = `5`
- n_jobs = `-1` (negative one) [it helps in using all the computational power to run this job]

(Note: Kindly ignore the warning.)

In [15]:
pipeline = Pipeline([
    ("poly_trans", PolynomialFeatures(interaction_only=True)),
    ("estimator", Lasso())
])

pipeline

Pipeline(steps=[('poly_trans', PolynomialFeatures(interaction_only=True)),
                ('estimator', Lasso())])

In [16]:
params = {
    "poly_trans__degree": [1, 2],
    "estimator__alpha": [10, 100, 1000, 10000],
}
cv_model = GridSearchCV(pipeline, params, scoring="neg_mean_absolute_error", cv=5, n_jobs=-1)
cv_model.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.830e+13, tolerance: 9.383e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.305e+13, tolerance: 9.505e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.204e+13, tolerance: 7.517e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.066e+13, tolerance: 9.320e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.613e+13, tolerance: 7.896e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.402e+14, tolerance: 9.383e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.850e+14, tolerance: 7.517e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.115e+14, tolerance: 9.505e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.199e+14, tolerance: 7.896e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.195e+12, tolerance: 7.517e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.074e+12, tolerance: 7.896e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.410e+14, tolerance: 9.320e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.826e+12, tolerance: 9.383e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.715e+13, tolerance: 9.505e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.598e+12, tolerance: 9.320e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.149e+12, tolerance: 9.383e+11
  model = cd_fast.enet_coordinate_descent(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.262e+11, tolerance: 7.896e+11
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('poly_trans',
                                        PolynomialFeatures(interaction_only=True)),
                                       ('estimator', Lasso())]),
             n_jobs=-1,
             param_grid={'estimator__alpha': [10, 100, 1000, 10000],
                         'poly_trans__degree': [1, 2]},
             scoring='neg_mean_absolute_error')

### Q6: Mark the best alpha value you got using above instructions.
- [ ] 10
- [ ] 100
- [x] 1000
- [ ] 10000

In [17]:
cv_model.best_params_["estimator__alpha"]

1000

### Q7: Enter the best polynomial degree value you got using above instructions.

In [18]:
cv_model.best_params_["poly_trans__degree"]

1

(Common Instructions for Question 16 and 17)

To Reduce the number of dimensions of the training dataset with PCA. Fit the PCA model using following parameter values on training data.

- `n_components= 13`
- `svd_solver='full'`
- `whiten=True`
- `random_state=27`

In [19]:
pca = PCA(n_components=13, svd_solver="full", whiten=True, random_state=27)
pca.fit(X_train, y_train)

PCA(n_components=13, random_state=27, svd_solver='full', whiten=True)

### Q8: What is the sum of explained_variance_ratio_ ? (upto two digits after the decimal)

In [20]:
round(pca.explained_variance_ratio_.sum(), 2)

0.97

### Q9: Use PCA transformed training feature matrix from earlier question and training labels to fit the RidgeCV estimator with cv=5 and having alpha values as [0.1,1,10,100,1000,10000]. Calculate the R2 score you got from the model for PCA transformed test dataset. (upto 4 digits after the decimal)

In [21]:
X_train_trans = pca.transform(X_train)
X_test_trans = pca.transform(X_test)

In [22]:
ridgecv_model = RidgeCV(alphas=[0.1, 1, 10, 100, 1000, 10000], cv=5)
ridgecv_model.fit(X_train_trans, y_train)

RidgeCV(alphas=[0.1, 1, 10, 100, 1000, 10000], cv=5)

In [23]:
round(ridgecv_model.score(X_test_trans, y_test), 4)

0.2964

(Common Instructions for Question 18-20)

Construct a pipeline to apply following steps

- STEP-1 Selecting 10 best features based on the f_regression score function.
- STEP-2 Apply Lasso algorithm with random_state=27 on that

In [24]:
lasso_pipeline = Pipeline([
    ("feature_selection", SelectKBest(f_regression, k=10)),
    ("model", Lasso(random_state=27))
])

lasso_pipeline

Pipeline(steps=[('feature_selection',
                 SelectKBest(score_func=<function f_regression at 0x7cbd8b0b2f80>)),
                ('model', Lasso(random_state=27))])

In [25]:
lasso_pipeline.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.875e+14, tolerance: 1.091e+12
  model = cd_fast.enet_coordinate_descent(

Pipeline(steps=[('feature_selection',
                 SelectKBest(score_func=<function f_regression at 0x7cbd8b0b2f80>)),
                ('model', Lasso(random_state=27))])

### Q10: What is the max P-VALUE you got for any feature of the train dataset?(upto 4 digits after the decimal)

In [26]:
round(lasso_pipeline.named_steps["feature_selection"].pvalues_.max(), 4)

0.8425

### Q11: What is the max F_STATISTICS score you got for any feature of the train dataset?  (upto 2 digits after the decimal)

In [27]:
round(lasso_pipeline.named_steps["feature_selection"].scores_.max(), 2)

21319.53

### Q12: What is the R2 score you got for this model using the test dataset? (upto 4 digits after the decimal)

In [28]:
round(lasso_pipeline.score(X_test, y_test), 4)

0.652