# MLP YYYY Term N OPPE

To be filled before the exam starts:

**Exam Name**: MLP OPPE

**Name of the student:** << Enter your full name>>

**Roll No. of the student:** << Enter your roll no.>>

**Date:** DD MM YYYY

In [1]:
import numpy as np
import pandas as pd

### Q. 1: Which dataset are you using for Data Preprocessing Part?

- [ ] Preprocessing1
- [ ] Preprocessing2
- [x] Preprocessing3
- [ ] Preprocessing4
- [ ] Preprocessing5

In [2]:
data = pd.read_csv("/kaggle/input/mlp-oppe-mock/Preprocessing3.csv")
data.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Greenwich,NaN,5187000.0,?,Detached House,3,2,1026.0,1.025953,South
1,2009-01-02,2009,Norwalk,NaN,480000.0,Single Family,Detached House,3,2,1051.0,1.025953,West
2,2009-01-02,2009,Waterbury,57890.0,152000.0,Single Family,Detached House,3,2,943.0,1.025953,East
3,2009-01-02,2009,NaN,44520.0,60000.0,Single Family,Detached House,3,2,1099.0,1.025953,North
4,2009-01-03,2009,Bridgeport,91071.0,250000.0,Two Family,Duplex,4,2,1213.0,1.025953,South

### Q. 2: What are the unique values present in the Locality feature of the dataset?
- [ ] [Detached House, Duplex, Triplex, Fourplex]
- [x] [Bridgeport, Fairfield, Greenwich, Norwalk,Stamford,Waterbury, West Hartford]
- [ ] [Boston, California, Greenwich, Stamford]
- [ ] [West Hartford, Waterbury, Norwalk]

In [3]:
data["Locality"].unique()

array(['Greenwich', 'Norwalk', 'Waterbury', nan, 'Bridgeport',
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

### Q. 3: Which of the following columns have categorical data?
- [ ] Estimated Value
- [x] Locality
- [x] Property
- [ ] num_bathrooms
- [x] Face

In [4]:
data.select_dtypes(include="object").columns

Index(['Date', 'Locality', 'Property', 'Residential', 'Face'], dtype='object')

### Q. 4: Which of the following features have `missing`(NaN) or unknown ("?") values present in the dataset?
- [ ] Year
- [x] Estimated Value
- [ ] Sale Price
- [x] Locality
- [x] Property
- [ ] property_tax_rate

In [5]:
nan_values = data.replace("?", np.nan).isnull().sum()
nan_values[nan_values > 0]

Locality           1285
Estimated Value    1281
Property           1873
carpet_area        1282
dtype: int64

### Q. 5: In the Year 2022, how many houses (rows) located in the Greenwich Locality have more than equal to 3 num_room, and facing towards either the North or East?

In [6]:
data_2022 = data[pd.to_datetime(data["Date"]).dt.year == 2022]
data_2022_filtered = data_2022[(data_2022["Locality"] == "Greenwich") & (data_2022["num_rooms"] >= 3)]
data_2022_filtered[data_2022_filtered["Face"].isin(["North", "East"])].shape[0]

35

### Q. 6: Split the dataset into train dataset and test dataset in the following manner

1. data(rows) collected before the year of 2021 [2009-2020] should be the train dataset
2. data(rows) collected in the year of 2021 and 2022 (both inclusive) should be the test dataset
3. columns except of the label vector should be the feature matrix (X_train or X_test)
4. make label vector (Y_train or y_test) containing values only from the target feature.

_How many rows are in the feature matrix of the test dataset ?_

In [7]:
data = data.replace("?", np.nan)

In [8]:
train_data = data[pd.to_datetime(data["Date"]).dt.year < 2021]
test_data = data[pd.to_datetime(data["Date"]).dt.year >= 2021]
train_data.shape, test_data.shape

((8272, 12), (1728, 12))

In [9]:
X_train = train_data.drop(columns="Sale Price")
y_train = train_data["Sale Price"]

X_train.head()

,Date,Year,Locality,Estimated Value,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Greenwich,NaN,NaN,Detached House,3,2,1026.0,1.025953,South
1,2009-01-02,2009,Norwalk,NaN,Single Family,Detached House,3,2,1051.0,1.025953,West
2,2009-01-02,2009,Waterbury,57890.0,Single Family,Detached House,3,2,943.0,1.025953,East
3,2009-01-02,2009,NaN,44520.0,Single Family,Detached House,3,2,1099.0,1.025953,North
4,2009-01-03,2009,Bridgeport,91071.0,Two Family,Duplex,4,2,1213.0,1.025953,South

In [10]:
X_test = test_data.drop(columns="Sale Price")
y_test = test_data["Sale Price"]

X_test.head()

,Date,Year,Locality,Estimated Value,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
8272,2021-01-02,2021,Stamford,NaN,NaN,Detached House,3,1,960.0,1.023495,North
8273,2021-01-03,2021,NaN,189370.0,Single Family,Detached House,3,3,1094.0,1.023495,North
8274,2021-01-03,2021,Bridgeport,106580.0,Single Family,Detached House,3,2,NaN,1.023495,East
8275,2021-01-03,2021,Stamford,313090.0,Single Family,Detached House,3,2,931.0,1.023495,North
8276,2021-01-03,2021,Bridgeport,102790.0,Single Family,Detached House,3,1,905.0,1.023495,West

In [11]:
X_test.shape[0]

1728

### Q. 7: Rules for Imputing the missing(NaN) or unknown ("?") values:

compute the instructed statistical values for different columns in train dataset only to repalce missing(NaN) and unknown("?") values respectively.
Replace the missing(NaN) and unknown("?") values from the train and test dataset with the instructed statistical values computed using the train dataset only.
Ignore the missing and unknown values while calculating the statistical values.

- Replace missing values(NaN) with the MOST FREQUENT value of the Locality feature

- Repalce missing values(NaN) with the MEDIAN value of the Estimated Value feature

- Replace missing values(NaN) with the MEAN value of the carpet_area feature

- Replace Unknown values("?") with the MOST FREQUENT value of the Property.


Write the answers related to the above imputation in below questions respectively.


Write the MEAN value of the carpet_area column of the train dataset you found to replace all the Missing Values (NaN). (upto 2 digits after decimal points)

In [12]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [13]:
X_train.head()

,Date,Year,Locality,Estimated Value,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Greenwich,NaN,NaN,Detached House,3,2,1026.0,1.025953,South
1,2009-01-02,2009,Norwalk,NaN,Single Family,Detached House,3,2,1051.0,1.025953,West
2,2009-01-02,2009,Waterbury,57890.0,Single Family,Detached House,3,2,943.0,1.025953,East
3,2009-01-02,2009,NaN,44520.0,Single Family,Detached House,3,2,1099.0,1.025953,North
4,2009-01-03,2009,Bridgeport,91071.0,Two Family,Duplex,4,2,1213.0,1.025953,South

In [14]:
round(X_train["carpet_area"].mean(), 2)

1113.4

In [15]:
preprocessor = ColumnTransformer([
    ("locality", SimpleImputer(strategy="most_frequent"), ["Locality"]),
    ("Estimated Value", SimpleImputer(strategy="median"), ["Estimated Value"]),
    ("carpet_area", SimpleImputer(strategy="mean"), ["carpet_area"]),
    ("property", SimpleImputer(strategy="most_frequent"), ["Property"])
], remainder='passthrough')

preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('locality',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Locality']),
                                ('Estimated Value',
                                 SimpleImputer(strategy='median'),
                                 ['Estimated Value']),
                                ('carpet_area', SimpleImputer(),
                                 ['carpet_area']),
                                ('property',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Property'])])

### Q. 8: What value you used to replace the unknown value ("?") in the Property column of the train dataset
- [x] Single Family
- [ ] Two Family
- [ ] Three Family
- [ ] Four Family

In [16]:
X_train["Property"].mode()

0    Single Family
Name: Property, dtype: object

### Q.9: Apply preprocessing on features of train and test datasets.

Drop the 'Date' Column before the preprocessing steps.
before applying any preprocessing there should not be any missing or unknown values present in the train and test dataset.
fitting (learning) should be done only on train dataset.
transform the test dataset using the fitting (learning) of train dataset

#### For Numerical Features
Scale the numerical feature of the feature matrix using the Min-Max Scaler

#### For Categorical Features
One-Hot Encode all categorical features(object columns) in the feature matrix


How many total features you got after one-hot encoding and scaling the training dataset?

- [ ] 10
- [ ] 12
- [x] 25
- [ ] 28

In [17]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

In [18]:
X_train.drop(columns="Date", inplace=True)
X_test.drop(columns="Date", inplace=True)

In [19]:
# X_train = preprocessor.fit_transform(X_train)
# X_test = preprocessor.transform(X_test)

# X_train[:5, ]

In [20]:
num_cols = X_train.select_dtypes(exclude="object").columns
cat_cols = X_train.select_dtypes(include="object").columns
num_cols, cat_cols

(Index(['Year', 'Estimated Value', 'num_rooms', 'num_bathrooms', 'carpet_area',
        'property_tax_rate'],
       dtype='object'),
 Index(['Locality', 'Property', 'Residential', 'Face'], dtype='object'))

In [21]:
col_transformer = ColumnTransformer([
    ('num', MinMaxScaler(), num_cols),
    ('cat', OneHotEncoder(), cat_cols)
], remainder='passthrough')

col_transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('num', MinMaxScaler(),
                                 Index(['Year', 'Estimated Value', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate'],
      dtype='object')),
                                ('cat', OneHotEncoder(),
                                 Index(['Locality', 'Property', 'Residential', 'Face'], dtype='object'))])

In [22]:
transformed_cols = ['Locality', 'Estimated Value', 'carpet_area', 'Property']
cols = transformed_cols + [col for col in X_train.columns if col not in transformed_cols]
cols

['Locality',
 'Estimated Value',
 'carpet_area',
 'Property',
 'Year',
 'Residential',
 'num_rooms',
 'num_bathrooms',
 'property_tax_rate',
 'Face']

In [23]:
X_train = pd.DataFrame(preprocessor.fit_transform(X_train), index=X_train.index, columns=cols)
X_test = pd.DataFrame(preprocessor.transform(X_test), index=X_test.index, columns=cols)

X_train.head()

,Locality,Estimated Value,carpet_area,Property,Year,Residential,num_rooms,num_bathrooms,property_tax_rate,Face
0,Greenwich,230360.0,1026.0,Single Family,2009,Detached House,3,2,1.025953,South
1,Norwalk,230360.0,1051.0,Single Family,2009,Detached House,3,2,1.025953,West
2,Waterbury,57890.0,943.0,Single Family,2009,Detached House,3,2,1.025953,East
3,Bridgeport,44520.0,1099.0,Single Family,2009,Detached House,3,2,1.025953,North
4,Bridgeport,91071.0,1213.0,Two Family,2009,Duplex,4,2,1.025953,South

In [24]:
X_train = col_transformer.fit_transform(X_train)
X_test = col_transformer.transform(X_test)

In [25]:
X_train.shape

(8272, 25)