### T2_2024 - NPPE 1 (Model Building)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iitmbs-mlp-nppe1/NPPE1_ModelBuilding1.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_Preprocessing1.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_Preprocessing3.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_ModelBuilding3.csv

Load the dataset.

    The file has no index column.
    The last column is the target column.
    The first row of the file has column ids.

### Q1: Which dataset are you using for this exam?
- [ ] NPPE1_ModelBuilding1.csv
- [ ] NPPE1_ModelBuilding2.csv
- [x] NPPE1_ModelBuilding3.csv
- [ ] NPPE1_ModelBuilding4.csv

In [2]:
df = pd.read_csv("/kaggle/input/iitmbs-mlp-nppe1/NPPE1_ModelBuilding3.csv")
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.087472,0.002829,1.768235,0.188396,0.117071,0.148148,0.478165,0.720443,0.967195,0.281563,0.428571,0.959596,1.0,0.0,23.358097
1,0.378379,0.022079,1.115629,0.091974,0.066089,0.851852,0.911759,0.785321,0.885001,0.424648,0.285714,0.868687,0.0,1.0,17.268768
2,0.066901,0.003828,-0.536262,0.221188,0.255671,0.296296,0.228024,0.406472,0.980184,0.274376,0.428571,0.767677,0.0,1.0,27.776974
3,0.140645,0.011132,1.323366,0.422514,0.153103,0.148148,0.410679,0.200319,0.861371,0.305006,0.142857,0.848485,0.0,1.0,16.121960
4,0.144225,0.204918,-0.930790,0.148694,0.177490,0.259259,0.146832,0.111429,0.983448,0.286322,0.285714,0.616162,1.0,0.0,23.129426

In [3]:
X = df.iloc[:, :14]
y = df["14"]

X.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.087472,0.002829,1.768235,0.188396,0.117071,0.148148,0.478165,0.720443,0.967195,0.281563,0.428571,0.959596,1.0,0.0
1,0.378379,0.022079,1.115629,0.091974,0.066089,0.851852,0.911759,0.785321,0.885001,0.424648,0.285714,0.868687,0.0,1.0
2,0.066901,0.003828,-0.536262,0.221188,0.255671,0.296296,0.228024,0.406472,0.980184,0.274376,0.428571,0.767677,0.0,1.0
3,0.140645,0.011132,1.323366,0.422514,0.153103,0.148148,0.410679,0.200319,0.861371,0.305006,0.142857,0.848485,0.0,1.0
4,0.144225,0.204918,-0.930790,0.148694,0.177490,0.259259,0.146832,0.111429,0.983448,0.286322,0.285714,0.616162,1.0,0.0

Split the dataset into train dataset and test dataset in the following manner
- Use train_test_split to split the dataset into train and test dataset with test size equal to 0.3(i.e.30%) and random_state equal to 42. Let other parameters have default values.
- Columns except the last column should be the feature matrix (X_train or X_test)
- Last column will be the label vector.

(Common instructions for Q.2, Q.3 and Q.4)

Train the ridge model on the training data with the following parameters:

- `alpha = 10`
- `solver = 'saga'`
- `tol = 1e-4`
- `random_state = 42`

### Q2: Enter the value of R2 score on the test dataset.

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

In [5]:
X.shape

(4000, 14)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((2800, 14), (1200, 14))

In [7]:
ridge_model = Ridge(alpha=10, solver="saga", random_state=42)   # default tol=1e-4
ridge_model.fit(X_train, y_train)

Ridge(alpha=10, random_state=42, solver='saga')

In [8]:
ridge_model.score(X_test, y_test)

0.6613547575262211

### Q3: What is the index of most important feature? Note the index starts from 0. Ignore the intercept for this question.

In [9]:
ridge_model.coef_

array([ -0.4825441 ,   3.74601838,  -0.73583331,   0.54199933,
        -9.89014109,   5.80114296,  -5.06099736,  -9.45015598,
         4.73124885, -23.51321982,  11.31863371,   0.49450664,
        -0.89196134,   0.89196134])

In [10]:
ridge_coef = abs(ridge_model.coef_)
ridge_coef

array([ 0.4825441 ,  3.74601838,  0.73583331,  0.54199933,  9.89014109,
        5.80114296,  5.06099736,  9.45015598,  4.73124885, 23.51321982,
       11.31863371,  0.49450664,  0.89196134,  0.89196134])

In [11]:
ridge_coef.argmax()

9

### Q4: What is the index of least important feature? Note the index starts from 0. Ignore the intercept for this question.

In [12]:
ridge_coef.argmin()

0

Take `SGDRegressor(random_state = 42)` estimator with GridSearchCV. 
Hyperparameter tuning to be done over the following parameters:
- penalty as `['l1', 'l2']`
- alpha values as `[1e-5, 1e-4, 1e-3, 1e-2, 1e-1]`
- values of tol as `[1e-4, 1e-3, 1e-2, 1e-1]`
- Use cross-validation = `5`
- Set scoring as `neg_mean_absolute_error`
Use the best model from above hyper parameter tuning process to answer following questions:

### Q5: What is the best penalty?
- [ ] `l1`
- [x] `l2`

In [13]:
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error

In [14]:
params = {
    "penalty": ["l1", "l2"],
    "alpha": [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1]
}

sgd_cv_model = GridSearchCV(SGDRegressor(random_state=42), params, cv=5, scoring="neg_mean_absolute_error")
sgd_cv_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [15]:
sgd_cv_model.best_params_["penalty"]

'l2'

### Q6: What will be value of mean absolute error on the test dataset?

In [16]:
-sgd_cv_model.score(X_test, y_test)

3.8131121797994014

In [17]:
mean_absolute_error(y_test, sgd_cv_model.predict(X_test))

3.8131121797994014

Create a pipeline of the `PCA()` as transformer and Lasso as an estimator.

Use GridSearchCV for tuning the hyperparameters of the created pipeline on training dataset.
- Values of n_components for PCA to be `[0.9, 0.95]`
- lasso alpha value to be taken as : `[10, 1, 0.01, 0.001]`
- scoring : `neg_mean_absolute_error`.
- Use $5$ fold cross validation.
- `n_jobs = -1` (negative one) [it helps in using all the computational power to run this job]
(Note: Kindly ignore the warning.)

### Q7: If we fit the pipeline on the training dataset, what will be the R2 score on the test dataset?

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

In [19]:
pipeline = Pipeline([
    ("PCA", PCA()),
    ("estimator", Lasso())
])
pipeline

Pipeline(steps=[('PCA', PCA()), ('estimator', Lasso())])

In [20]:
params = {
    "PCA__n_components": [0.9, 0.95],
    "estimator__alpha": [10, 1, 0.01, 0.001],
}

lasso_cv_model = GridSearchCV(pipeline, params, scoring="neg_mean_absolute_error", cv=5, n_jobs=-1)
lasso_cv_model.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('PCA', PCA()), ('estimator', Lasso())]),
             n_jobs=-1,
             param_grid={'PCA__n_components': [0.9, 0.95],
                         'estimator__alpha': [10, 1, 0.01, 0.001]},
             scoring='neg_mean_absolute_error')

In [21]:
r2_score(y_test, lasso_cv_model.predict(X_test))

0.6288625430197571

### Q8: How much variance is explained (Eigen value) by the first principle component?

In [22]:
lasso_cv_model.best_estimator_.named_steps["PCA"].explained_variance_[0]

1.1635075742239032

Create a pipeline of the PolynomialFeatures as transformer and Lasso as an estimator with the following parameters:
  - For PolynomialFeatures:
    - interaction_only = False
    - degree = 2
  - For Lasso:
    - alpha = 1
    - warm_start = True
    - random state as 0

### Q9: Fit the pipeline on the training dataset and find the R2R2 score on the test dataset.

In [23]:
from sklearn.preprocessing import PolynomialFeatures

In [24]:
pipeline = Pipeline([
    ("poly", PolynomialFeatures()),
    ("estimator", Lasso(alpha=1, warm_start=True, random_state=0))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('estimator', Lasso(alpha=1, random_state=0, warm_start=True))])

In [25]:
pipeline.score(X_test, y_test)

0.157678032410551

### Q10: If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?

- Type the index of the eliminated feature (index starts from 0).
- Use `LinearRegression` model with default parameters as an estimator.
- Use processed training data.

In [26]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [27]:
rfe = RFE(LinearRegression())
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression())

In [28]:
rfe.ranking_

array([4, 2, 8, 7, 1, 1, 1, 1, 1, 1, 1, 6, 5, 3])

In [29]:
rfe.ranking_.argmax()

2

### Ref:

#### [Sklearn Quick Reference 🔗](https://drive.google.com/file/d/1_yNY2WjFmDRx4X2XdG1qwLFmihLZdWkm/view?usp=sharing)
#### [Dataset 🔗](https://drive.google.com/file/d/1DRtaP8QnU7SFrhMsdR67TBNuq5aOusUe/view?usp=sharing)