# MLP Session 13a - OPPE 1 Revision 2 with Practice Questions by Parampreet Singh
## [Session video 🔗](https://youtu.be/4x6mFTG5oEg)

- 20+ New Practice Questions
- Concepts Revision from Week 1 to Week 5

# [Practice Set 2, 30+ Questions 🔗](https://www.kaggle.com/code/param302/session-13b-oppe-1-revision-2-by-parampreet/)

### Mock OPPE 1 Solutions
- [Mock OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-1)
- [Mock OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-2)

### NPPE 1 Solutions
- [NPPE OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part1)
- [NPPE OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part2)

#### [Session Playlist 🔗](https://www.youtube.com/playlist?list=PLClULgPbRPsA1twUfMlWkI4yJeqjsSi23)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:
df = pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

## Data Preprocessing

### Q1: How many samples are there in the dataset?

In [5]:
df.shape[0]

1460

### Q2: What is the median house price (in lacs)?

In [6]:
np.median(df["SalePrice"])

163000.0

In [7]:
df["SalePrice"].median()

163000.0

### Q3: How many houses have 3 or more Bedroom?

In [8]:
(df["BedroomAbvGr"] >= 3).sum()

1046

### Q4: What is the average price of the top 5 most expensive houses (in lacs)?

In [9]:
(df["SalePrice"].sort_values(ascending=False)[:5]).mean()

663918.0

In [10]:
df["SalePrice"].nlargest(5).mean()

663918.0

### Q5: What is the total number of missing or unknown values in the garage area feature?
> **Hint**: Carefully look at the values the feature takes and find out implausible value.

In [11]:
df["GarageArea"].isna().sum()

0

In [12]:
df["Alley"].unique()

array([nan, 'Grvl', 'Pave'], dtype=object)

In [13]:
df["Alley"].isna().sum()

1369

### Q6: What is the total number of missing or unknown values in the year built feature?
> **Hint**: Carefully look at the values the feature takes and find out implausible value.

In [14]:
df["YearBuilt"].unique()

array([2003, 1976, 2001, 1915, 2000, 1993, 2004, 1973, 1931, 1939, 1965,
       2005, 1962, 2006, 1960, 1929, 1970, 1967, 1958, 1930, 2002, 1968,
       2007, 1951, 1957, 1927, 1920, 1966, 1959, 1994, 1954, 1953, 1955,
       1983, 1975, 1997, 1934, 1963, 1981, 1964, 1999, 1972, 1921, 1945,
       1982, 1998, 1956, 1948, 1910, 1995, 1991, 2009, 1950, 1961, 1977,
       1985, 1979, 1885, 1919, 1990, 1969, 1935, 1988, 1971, 1952, 1936,
       1923, 1924, 1984, 1926, 1940, 1941, 1987, 1986, 2008, 1908, 1892,
       1916, 1932, 1918, 1912, 1947, 1925, 1900, 1980, 1989, 1992, 1949,
       1880, 1928, 1978, 1922, 1996, 2010, 1946, 1913, 1937, 1942, 1938,
       1974, 1893, 1914, 1906, 1890, 1898, 1904, 1882, 1875, 1911, 1917,
       1872, 1905])

In [15]:
df["YearBuilt"].isnull().sum()

0

### Q7: What is the total number of missing or unknown values in the CENTRAL_AIR feature?
> **Hint**: Carefully look at the values the feature takes and find out implausible value.

In [16]:
df["CentralAir"].unique()

array(['Y', 'N'], dtype=object)

In [17]:
df["CentralAir"].isna().sum()

0

### Q8: How many houses have a garage and were built within the last 30 years (i.e., a house 30 years old or younger)? For this question, ignore the rows that have missing values in either garage or year built feature.

In [18]:
# most recent year / latest year

df["GarageYrBlt"].sort_values(ascending=False).iloc[0]

2010.0

In [19]:
df["GarageYrBlt"].max()

2010.0

In [20]:
most_recent_year = df["GarageYrBlt"].nlargest(1).iloc[0]
most_recent_year-30

1980.0

In [21]:
df[df["GarageYrBlt"] > most_recent_year-30].shape[0]

678

In [22]:
(df["GarageYrBlt"] > most_recent_year-30).sum()

678

### Q9: How many houses have more than 1 kitchen?

In [23]:
(df["KitchenAbvGr"] > 1).sum()

67

In [24]:
df[df["KitchenAbvGr"] > 1].shape[0]

67

Create a column 'CATEGORY' and divide the houses in categories as following:

- Category 1: house price <10 lacs
- Category 2: 10 lacs <= house price <20 lacs
- Category 3: 20 lacs <= house price <30 lacs
- Category 4: 30 lacs <= house price <40 lacs
- Category 5: house price >=40 lacs

### Q10: Which category has the highest number of records?

Nan values: np.nan, -1, -2, -ve, "UNKNOWN", "-", "_", "missing", "?"

In [25]:
def get_category(price):
    if price < 100000:
        return "Category 1"
    elif price < 200000:
        return "Category 2"
    elif 200000 <= price < 300000:
        return "Category 3"
    elif 300000 <= price < 400000:
        return "Category 4"
    return "Category 5"

In [26]:
df["Category"] = df["SalePrice"].apply(get_category)

In [27]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Category
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,Category 3
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,Category 2
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,Category 3
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,Category 2
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,Category 3

In [28]:
df.drop(columns="Category", inplace=True)

In [29]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

Apply Preprocessing
Divide the data into training and test sets

1. Replace the respective missing or unknown values in features garage area, year built, and central air with `np.nan`.
2. Keep 30% of the data as test set.
3. Use `random_state` as 0.
4. `SalePrice` is the target, rest of the columns are the features.
5. Apply train-test split.

> **Hint**: Look for the documentation of the usual function that divides the data into training and test datasets.

### Q11: What is the number of samples in the training set?

In [30]:
X = df.drop(columns="SalePrice")
y = df["SalePrice"]

In [31]:
X.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

((1022, 80), (438, 80))

In [34]:
X_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
64,65,60,RL,NaN,9375,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,2,2009,WD,Normal
682,683,120,RL,NaN,2887,Pave,NaN,Reg,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,11,2008,WD,Normal
960,961,20,RL,50.0,7207,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
1384,1385,50,RL,60.0,9060,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,10,2009,WD,Normal
1100,1101,30,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,1,2009,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,764,60,RL,82.0,9430,Pave,NaN,Reg,Lvl,AllPub,...,180,0,NaN,NaN,NaN,0,7,2009,WD,Normal
835,836,20,RL,60.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
1216,1217,90,RM,68.0,8930,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
559,560,120,RL,NaN,3196,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
684,685,60,RL,58.0,16770,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal

In [35]:
X_train.shape[0]

1022

Apply the following preprocessing steps:

1. Drop CATEGORY column.
2. MSSubClass: MinMax scaling
3. LotArea: MinMax scaling
4. YearBuilt: Standard scaling
5. GrLivArea: MinMax scaling
6. FullBath: MinMax scaling
7. BedroomAbvGr: MinMax scaling
8. TotRmsAbvGrd: MinMax scaling
9. GarageCars: MinMax scaling
10. GarageArea: MinMax scaling
11. LotFrontage: Impute with median then MinMax scaling
12. OverallQual: Impute with mean then MinMax scaling
13. CentralAir: Impute with most frequent value then one hot encode.

**NOTE**:
1. Make sure to preprocess the features in exactly the above order. The answer of Q.16 depends upon the correct order of feature processing.
2. You may have to use multiple instances of a transformer for this question.

### Q12: How many features are there after performing the above transformation?

In [36]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

11. LotFrontage: Impute with median then MinMax scaling
12. OverallQual: Impute with mean then MinMax scaling
13. CentralAir: Impute with most frequent value then one hot encode.

In [37]:
X_train.shape

(1022, 80)

In [38]:
transformer = ColumnTransformer([
    ("minmaxscaler", MinMaxScaler(), ["MSSubClass", "LotArea"]),
    ("LotFrontage", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("minmaxscaler", MinMaxScaler())
    ]), ["LotFrontage"]),
    ("OverallQual", Pipeline([
        ("imputer", SimpleImputer(strategy="mean")),
        ("minmaxscaler", MinMaxScaler())
    ]), ["OverallQual"]),
    ("CentralAir", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder())
    ]), ["CentralAir"])
], remainder="passthrough")
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('minmaxscaler', MinMaxScaler(),
                                 ['MSSubClass', 'LotArea']),
                                ('LotFrontage',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('minmaxscaler',
                                                  MinMaxScaler())]),
                                 ['LotFrontage']),
                                ('OverallQual',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('minmaxscaler',
                                                  MinMaxScaler())]),
                                 ['OverallQual']),
                                ('CentralAir',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', OneHotEncoder())]),
                                 ['CentralAir'])])

mean

fit - compute values

transform: replace missing values with mean values (computed values)

fit_transform: fit & transform

In [39]:
transformer.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('minmaxscaler', MinMaxScaler(),
                                 ['MSSubClass', 'LotArea']),
                                ('LotFrontage',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('minmaxscaler',
                                                  MinMaxScaler())]),
                                 ['LotFrontage']),
                                ('OverallQual',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('minmaxscaler',
                                                  MinMaxScaler())]),
                                 ['OverallQual']),
                                ('CentralAir',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', OneHotEncoder())]),
                                 ['CentralAir'])])

In [40]:
transformer.fit_transform(X_train)

array([[0.2352941176470588, 0.03774334525228446, 0.1643835616438356, ...,
        2009, 'WD', 'Normal'],
       [0.588235294117647, 0.0074177942929257515, 0.1643835616438356,
        ..., 2008, 'WD', 'Normal'],
       [0.0, 0.027609899740587536, 0.09931506849315068, ..., 2010, 'WD',
        'Normal'],
       ...,
       [0.4117647058823529, 0.03566337142723597, 0.16095890410958902,
        ..., 2010, 'WD', 'Normal'],
       [0.588235294117647, 0.00886209072425156, 0.1643835616438356, ...,
        2006, 'WD', 'Normal'],
       [0.2352941176470588, 0.07230830353595549, 0.1267123287671233, ...,
        2010, 'WD', 'Normal']], dtype=object)

In [41]:
transformer.transform(X_test)

array([[0.0, 0.14661712122274417, 0.1643835616438356, ..., 2007, 'WD',
        'Alloca'],
       [0.17647058823529413, 0.03828086657785879, 0.19863013698630133,
        ..., 2006, 'WD', 'Normal'],
       [0.17647058823529413, 0.026712472831802565, 0.1643835616438356,
        ..., 2009, 'WD', 'Normal'],
       ...,
       [0.0, 0.042707237841501315, 0.23972602739726023, ..., 2008, 'WD',
        'Normal'],
       [0.0, 0.0397672298955339, 0.15753424657534243, ..., 2009, 'WD',
        'Normal'],
       [0.0, 0.05430835027694033, 0.2705479452054794, ..., 2010, 'New',
        'Partial']], dtype=object)

### Q13: What is the mean of the transformed test data (features only)?
> **Note**: Compute the mean of the whole feature matrix i.e., mean of all values in the transformed test feature matrix.

## Model Building:

In [42]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

Split the dataset into train dataset and test dataset in the following manner:
- Use `train_test_split` to split the dataset into train and test dataset with test size equal to 0.3 (i.e., 30%) and `random_state` equal to 42. Let other parameters have default values.
- Columns except the last column should be the feature matrix (`X_train` or `X_test`).
- The last column will be the label vector.

(Common instructions for Q.2, Q.3, and Q.4)

Train the ridge model on the training data with the following parameters:
- `alpha` = 10
- `solver` = 'saga'
- `tol` = 1e-4
- `random_state` = 42

### Q1: Enter the value of R2 score on the test dataset.

In [43]:
df2 = df.select_dtypes(exclude="object").dropna()

In [44]:
X = df2.drop(columns="SalePrice")
y = df2["SalePrice"]

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)
X_train.shape, X_test.shape

((784, 37), (337, 37))

$$f(x) = w^Tx + b$$

- $w$ - weights, coefficients, coef_
- $b$ - bias, intercept

In [46]:
from sklearn.linear_model import Ridge

In [47]:
ridge_model = Ridge(alpha=10, solver="saga", random_state=42)
ridge_model.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

Ridge(alpha=10, random_state=42, solver='saga')

In [48]:
from sklearn.metrics import r2_score

In [49]:
y_preds = ridge_model.predict(X_test)

In [50]:
r2_score(y_test, y_preds)

0.7005488934111169

In [51]:
ridge_model.score(X_test, y_test)

0.7005488934111169

### Q2: What is the index of the most important feature? Note the index starts from 0. Ignore the intercept for this question.

In [52]:
np.abs(ridge_model.coef_).argmax()

16

### Q3: What is the index of the least important feature? Note the index starts from 0. Ignore the intercept for this question.

In [53]:
np.abs(ridge_model.coef_).argmin()

18

In [54]:
ridge_model.intercept_

-33131.81804878349

Take `SGDRegressor(random_state=42)` estimator with `GridSearchCV`. 
Hyperparameter tuning to be done over the following parameters:
- `penalty` as `['l1', 'l2']`
- `alpha` values as `[1e-5, 1e-4, 1e-3, 1e-2, 1e-1]`
- values of `tol` as `[1e-4, 1e-3, 1e-2, 1e-1]`
- Use `cross-validation` = 5
- Set scoring as `neg_mean_absolute_error`
Use the best model from the above hyperparameter tuning process to answer the following questions:

### Q4: What is the best penalty?
- [ ] l1
- [x] l2

In [55]:
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV

In [56]:
params = {
    "penalty": ["l1", "l2"],
    "alpha": [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1]
}

In [57]:
sgd_cv_model = GridSearchCV(SGDRegressor(random_state=42), params, cv=5, scoring="neg_mean_absolute_error")
sgd_cv_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [58]:
sgd_model = SGDRegressor(random_state=42)
sgd_cv_model = GridSearchCV(sgd_model, params, cv=5, scoring="neg_mean_absolute_error")
sgd_cv_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [59]:
sgd_cv_model.best_params_

{'alpha': 0.1, 'penalty': 'l2', 'tol': 0.0001}

In [60]:
sgd_cv_model.best_params_["penalty"]

'l2'

In [61]:
sgd_cv_model.best_estimator_.penalty

'l2'

### Q5: What will be the value of the mean absolute error on the test dataset?

In [62]:
from sklearn.metrics import mean_absolute_error

In [63]:
y_preds = sgd_cv_model.predict(X_test)

In [64]:
mean_absolute_error(y_test, y_preds)

4.015500267955764e+16

In [65]:
-sgd_cv_model.score(X_test, y_test)

4.015500267955764e+16

In [66]:
r2_score(y_test, y_preds)

-3.0195168359818137e+23



Create a pipeline of the `PCA()` as transformer and `Lasso` as an estimator.
Use `GridSearchCV` for tuning the hyperparameters of the created pipeline on the training dataset.
- Values of `n_components` for PCA to be `[0.9, 0.95]`
- `lasso alpha` value to be taken as: `[10, 1, 0.01, 0.001]`
- scoring: `neg_mean_absolute_error`.
- Use 5 fold cross-validation.
- `n_jobs` = -1 (negative one) [it helps in using all the computational power to run this job]
> **Note**: Kindly ignore the warning.

In [67]:
from sklearn.decomposition import PCA
from sklearn.linear_model import Lasso

In [68]:
model_pipeline = Pipeline([
    ("transformer", PCA()),
    ("estimator", Lasso())
])
model_pipeline

Pipeline(steps=[('transformer', PCA()), ('estimator', Lasso())])

In [69]:
params = {
    "transformer__n_components": [0.9, 0.95],
    "estimator__alpha": [10, 1, 0.01, 0.001],
}

In [70]:
cv_model = GridSearchCV(model_pipeline, params, scoring="neg_mean_absolute_error", cv=5, n_jobs=-1)
cv_model.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('transformer', PCA()),
                                       ('estimator', Lasso())]),
             n_jobs=-1,
             param_grid={'estimator__alpha': [10, 1, 0.01, 0.001],
                         'transformer__n_components': [0.9, 0.95]},
             scoring='neg_mean_absolute_error')

### Q6: If we fit the pipeline on the training dataset, what will be the R2 score on the test dataset?

In [71]:
cv_model.score(X_test, y_test)

-58966.37753066937

In [72]:
r2_score(y_test, cv_model.predict(X_test))

0.09217960913031731

### Q7: How much variance is explained (Eigen value) by the first principal component?

In [73]:
cv_model.best_params_

{'estimator__alpha': 10, 'transformer__n_components': 0.9}

In [74]:
cv_model.best_estimator_

Pipeline(steps=[('transformer', PCA(n_components=0.9)),
                ('estimator', Lasso(alpha=10))])

In [75]:
cv_model.best_estimator_.named_steps

{'transformer': PCA(n_components=0.9), 'estimator': Lasso(alpha=10)}

In [76]:
cv_model.best_estimator_.named_steps["transformer"]

PCA(n_components=0.9)

In [77]:
cv_model.best_estimator_.named_steps["transformer"].explained_variance_[0]

85989271.63151763

In [78]:
cv_model.best_estimator_.named_steps["transformer"].explained_variance_ratio_

array([0.98271466])

Create a pipeline of the `PolynomialFeatures` as transformer and `Lasso` as an estimator with the following parameters:
- For `PolynomialFeatures`:
  - `interaction_only` = False
  - `degree` = 2
- For `Lasso`:
  - `alpha` = 1
  - `warm_start` = True
  - `random_state` as 0

### Q8: Fit the pipeline on the training dataset and find the R2 score on the test dataset.

In [79]:
from sklearn.preprocessing import PolynomialFeatures

In [80]:
model_pipeline = Pipeline([
    ("poly", PolynomialFeatures(interaction_only=False)),
    ("estimator", Lasso(alpha=1, warm_start=True, random_state=0))
])
model_pipeline

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('estimator', Lasso(alpha=1, random_state=0, warm_start=True))])

In [81]:
model_pipeline.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.370e+10, tolerance: 5.003e+08
  model = cd_fast.enet_coordinate_descent(

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('estimator', Lasso(alpha=1, random_state=0, warm_start=True))])

In [82]:
model_pipeline.score(X_test, y_test)

0.5329248744805843

In [83]:
r2_score(y_test, model_pipeline.predict(X_test))

0.5329248744805843

### Q9: If you eliminate 1 feature with recursive feature elimination, which feature will be eliminated?
- Type the index of the eliminated feature (index starts from 0).
- Use `LinearRegression` model with default parameters as an estimator.
- Use processed training data.

In [84]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [85]:
rfe = RFE(LinearRegression())
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression())

In [86]:
rfe.ranking_

array([17,  1,  5, 20,  1,  1,  1,  4,  6, 18, 13, 16, 15,  9, 10,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  3,  1, 11,  8, 19, 14,  7,  2,  1,
       12,  1,  1])

In [87]:
rfe.ranking_.argmax()

3

Create a pipeline with the following steps:
1. Impute missing values in 'BsmtFinSF1' with KNNImputer(n_neighbors=3)
2. Impute missing values in 'LotFrontage' with SimpleImputer(strategy='median')
3. Impute rest of the columns with their mean value.
4. Apply StandardScaler to 'TotalBsmtSF'
5. One-hot encode 'MSZoning'
6. Ordinal Encoder rest of the columns
7. Use SelectKBest with mutual_info_regression to select the top 5 features
8. Train a Ridge regression model with alpha=10

### Q10: What is the R2 score on the test dataset?

Create a pipeline with the following steps:
1. Impute missing values in 'Electrical' with SimpleImputer(strategy='most_frequent')
2. Impute rest of the columns with their mean value.
3. Scale '2ndFlrSF' using StandardScaler
4. One-hot encode 'HouseStyle'
5. Ordinal Encoder rest of the columns
6. Train a Lasso regression model with alpha=0.1

### Q11: What is the mean squared error on the test dataset?

# MLP Session 13a - OPPE 1 Revision 2 with Practice Questions by Parampreet Singh
## [Session video 🔗](https://youtu.be/4x6mFTG5oEg)

- 20+ New Practice Questions
- Concepts Revision from Week 1 to Week 5

# [Practice Set 2, 30+ Questions 🔗](https://www.kaggle.com/code/param302/session-13b-oppe-1-revision-2-by-parampreet/)

### Mock OPPE 1 Solutions
- [Mock OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-1)
- [Mock OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-2)

### NPPE 1 Solutions
- [NPPE OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part1)
- [NPPE OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part2)

#### [Session Playlist 🔗](https://www.youtube.com/playlist?list=PLClULgPbRPsA1twUfMlWkI4yJeqjsSi23)