# MLP Session 19a - OPPE 2 Revision by Parampreet Singh
## [Session video 🔗](https://youtu.be/9AlIXXQE86M)

- Concepts Revision from Week 1 to Week 10

# [Practice Set 1, 20+ Questions 🔗](https://www.kaggle.com/code/param302/session-13a-oppe-1-revision-2-by-parampreet/)
# [Practice Set 2, 30+ Questions 🔗](https://www.kaggle.com/param302/session-19b-oppe-2-revision-by-parampreet-singh)

### Mock OPPE 1 Solutions
- [Mock OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-1)
- [Mock OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-2)

### NPPE 1 Solutions
- [NPPE OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part1)
- [NPPE OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part2)

#### [Session Playlist 🔗](https://www.youtube.com/playlist?list=PLClULgPbRPsA1twUfMlWkI4yJeqjsSi23)

## NPPE 2 Solutions

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iitmbs-mlp-nppe2/T124OPPE2_Preprocessing_V1.csv
/kaggle/input/iitmbs-mlp-nppe2/T124OPPE2_ModelBuilding_V1.csv

Gender: Gender of the patient.

HasTension: If the patient is known to have hyper tension.

Age: Age of the patient in years.

AnyHeartDisease: If the patient is known to have any cardio pathy.

NeverMarried: Status of the patient if he/she was never married.

Occupation: Occupation or job type of the patient.

LivesIn: If the patient lives in a city or village.

GlucoseLevel: Randomly sampled glucose level of a patient.

BMI: Body mass index.

SmokingStatus: How frequent a patient smokes or if he has smoked before.

HeartAttack: If the patient has a cardiac arrest before.

In [2]:
df = pd.read_csv("/kaggle/input/iitmbs-mlp-nppe2/T124OPPE2_Preprocessing_V1.csv")
df.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
0,Female,75.0,Yes,No,Yes,Self-employed,City,54.6,35.1,never smoked,No
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes,No
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes,No
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,Unknown,Yes
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4000 non-null   object
 1   Age              4000 non-null   float64
 2   HasTension       4000 non-null   object
 3   AnyHeartDisease  4000 non-null   object
 4   NeverMarried     4000 non-null   object
 5   Occupation       4000 non-null   object
 6   LivesIn          4000 non-null   object
 7   GlucoseLevel     4000 non-null   float64
 8   BMI              3851 non-null   float64
 9   SmokingStatus    4000 non-null   object
 10  HeartAttack      4000 non-null   object
dtypes: float64(3), object(8)
memory usage: 343.9+ KB

In [4]:
df.isna().sum()

Gender               0
Age                  0
HasTension           0
AnyHeartDisease      0
NeverMarried         0
Occupation           0
LivesIn              0
GlucoseLevel         0
BMI                149
SmokingStatus        0
HeartAttack          0
dtype: int64

In [5]:
df.describe()

               Age  GlucoseLevel          BMI
count  4000.000000   4000.000000  3851.000000
mean     43.158820    106.014875    28.857959
std      22.704668     45.497055     7.904360
min      -3.000000     -2.000000     9.600000
25%      25.000000     77.075000    23.500000
50%      45.000000     91.900000    27.900000
75%      61.000000    114.100000    33.200000
max      82.000000    272.200000    97.000000

### Q2: What is the total number of missing or unknown values in the column Gender?

In [6]:
df["Gender"].isna().sum()

0

In [7]:
df["Gender"].unique()

array(['Female', 'Male', 'Unknown'], dtype=object)

In [8]:
df["Gender"].value_counts()

Gender
Female     2366
Male       1627
Unknown       7
Name: count, dtype: int64

In [9]:
df["Gender"].value_counts()["Unknown"]

7

### Q3: What is the total number of missing or unknown values in the column Age?

In [10]:
df["Age"].isna().sum()

0

In [11]:
df["Age"].min()

-3.0

In [12]:
df[df["Age"] < 0]["Age"].shape

(8,)

### Q4: What is the total number of missing or unknown values in the column GlucoseLevel?

In [13]:
df["GlucoseLevel"].isna().sum()

0

In [14]:
df["GlucoseLevel"].min()

-2.0

In [15]:
df[df["GlucoseLevel"] < 0]["GlucoseLevel"].shape

(9,)

### Q5: What is the total number of missing or unknown values in the column LivesIn?

In [16]:
df["LivesIn"].isna().sum()

0

In [17]:
df["LivesIn"].unique()

array(['City', 'Village', 'Unknown'], dtype=object)

In [18]:
df["LivesIn"].value_counts()

LivesIn
City       2030
Village    1965
Unknown       5
Name: count, dtype: int64

### Q6: What is the total number of missing or unknown values in the column BMI?

In [19]:
df["BMI"].isnull().sum()

149

In [20]:
df["BMI"].min()

9.6

### Q7: What is the total number of missing or unknown values in the column SmokingStatus?

In [21]:
df["SmokingStatus"].isnull().sum()

0

In [22]:
df["SmokingStatus"].value_counts()

SmokingStatus
never smoked       1502
Unknown            1204
formerly smoked     697
smokes              597
Name: count, dtype: int64

### Q8: What is the mean value of the BMI in the dataset? Ignore the missing values if any

In [23]:
df["BMI"].mean()

28.857958971695663

In [24]:
df["Age"].mean()

43.15881999999999

In [25]:
df[df["Age"] > 0]["Age"].mean()

43.25132264529057

### Q9: How many people live in city, smoked at least once in life and had a heartattack? Ignore records/rows with any missing values.

In [26]:
df.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
0,Female,75.0,Yes,No,Yes,Self-employed,City,54.6,35.1,never smoked,No
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes,No
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes,No
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,Unknown,Yes
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked,No

In [27]:
smoked = ["smokes", "formerly smoked"]

In [28]:
df[(df["LivesIn"]=="City") & (df["SmokingStatus"].isin(smoked)) & (df["HeartAttack"]=="Yes")].shape[0]

52

### Q10: Which of the following categories have highest frequency? Ignore rows with missing values.
- [ ] female patients without tension, without any heart disease and never married
- [ ] female patients without tension, without any heart disease and either currently married or married before
- [ ] male patients without tension, without any heart disease and never married
- [ ] male patients with tension, with a heart disease and never married
- [ ] There is a tie between 2 or more options.

### Q11: Select columns with categorical values :

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4000 non-null   object
 1   Age              4000 non-null   float64
 2   HasTension       4000 non-null   object
 3   AnyHeartDisease  4000 non-null   object
 4   NeverMarried     4000 non-null   object
 5   Occupation       4000 non-null   object
 6   LivesIn          4000 non-null   object
 7   GlucoseLevel     4000 non-null   float64
 8   BMI              3851 non-null   float64
 9   SmokingStatus    4000 non-null   object
 10  HeartAttack      4000 non-null   object
dtypes: float64(3), object(8)
memory usage: 343.9+ KB

In [30]:
df.select_dtypes(include="object").columns

Index(['Gender', 'HasTension', 'AnyHeartDisease', 'NeverMarried', 'Occupation',
       'LivesIn', 'SmokingStatus', 'HeartAttack'],
      dtype='object')

### Q12: 'HeartAttack' is the target column. What is the distribution count of "No" and "Yes" classes?

In [31]:
df["HeartAttack"].value_counts()

HeartAttack
No     3806
Yes     194
Name: count, dtype: int64

In [32]:
df["HeartAttack"].value_counts(normalize=True)

HeartAttack
No     0.9515
Yes    0.0485
Name: proportion, dtype: float64

### Q13: Divide the data into training and test sets

Keep 30% of the data as test set. 

Use random_state as 0

HeartAttack is the target, rest of the columns are the features.

 For the label/target vector, replace "Yes" with 1 and "No" with 0.
 
 Divide the dataset into training and test sets keeping target(y) in stratified manner.

Hint: look for the documentation of the usual function that divides the data into training and test datasets.

Prepare a data preprocessing pipeline to process features in following order:

    Gender: Impute with most frequent then ordinally encode.
    Age: Impute with mean then standard scale.
    HasTension: Ordinally encode.
    AnyHeartDisease:Ordinally encode.
    NeverMarried:Ordinally encode.
    Occupation: One hot encode.
    LivesIn: Impute with most frequent then ordinally encode.
    GlucoseLevel: Impute with mean, then min-max scaling.
    BMI: Impute with mean, then standard scale.
    SmokingStatus: Impute with most frequent, then one hot encode


Hint: After transformation, your feature matrix must have columns in following order:

	0. Gender
	1. Age
	2. HasTension
	3. AnyHeartDisease
	4. NeverMarried
	5. Occupation_Govt_job
	6. Occupation_Never_worked
	7. Occupation_Private
	8. Occupation_Self-employed
	9. Occupation_children
	10. LivesIn
	11. GlucoseLevel
	12. BMI
	13. SmokingStatus_formerly smoked
	14. SmokingStatus_never smoked
	15. SmokingStatus_smokes

NOTE:

Make sure to preprocess the features in the above order exactly. Answer(s) of later question(s) depend(s) upon correct order of featuring processing.

You may have to use multiple instances of a trasnformer for this question.

Calculate the shape of the feature matrix of training dataset.

In [33]:
X = df.drop(columns="HeartAttack")
y = df["HeartAttack"].copy()

In [34]:
X.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus
0,Female,75.0,Yes,No,Yes,Self-employed,City,54.6,35.1,never smoked
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,Unknown
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked

In [35]:
y = y.replace({"Yes": 1, "No": 0})
y.head()

/tmp/ipykernel_18/1027615507.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({"Yes": 1, "No": 0})

0    0
1    0
2    0
3    1
4    0
Name: HeartAttack, dtype: int64

In [36]:
y.value_counts()

HeartAttack
0    3806
1     194
Name: count, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,  random_state=0, stratify=y)

In [39]:
X_train.shape, X_test.shape

((2800, 10), (1200, 10))

In [40]:
train_idx, test_idx = [*StratifiedShuffleSplit(1, test_size=0.3, random_state=0).split(X, y)][0]

In [41]:
class DataFrameMaker(BaseEstimator, TransformerMixin):
    def __init__(self, transformer):
        self.transformer = transformer

    def fit(self, X, y=None):
        self.transformer.fit(X)
        self.columns = [i.split("__")[-1] for i in self.transformer.get_feature_names_out()]
        return self

    def transform(self, X):
        index = X.index
        X = self.transformer.transform(X)
        X = pd.DataFrame(X, index=index, columns=self.columns)
        for col in self.columns:
            try:
                X[col] = pd.to_numeric(X[col])
            except ValueError:
                pass
        return X
    
    def get_feature_names_out(self, names):
        return names

In [42]:
cat_cols = X_train.select_dtypes(include="object").columns
num_cols = X_train.select_dtypes(exclude="object").columns
cat_cols, num_cols

(Index(['Gender', 'HasTension', 'AnyHeartDisease', 'NeverMarried', 'Occupation',
        'LivesIn', 'SmokingStatus'],
       dtype='object'),
 Index(['Age', 'GlucoseLevel', 'BMI'], dtype='object'))

    Gender: Impute with most frequent then ordinally encode.
    Age: Impute with mean then standard scale.
    HasTension: Ordinally encode.
    AnyHeartDisease:Ordinally encode.
    NeverMarried:Ordinally encode.
    Occupation: One hot encode.
    LivesIn: Impute with most frequent then ordinally encode.
    GlucoseLevel: Impute with mean, then min-max scaling.
    BMI: Impute with mean, then standard scale.
    SmokingStatus: Impute with most frequent, then one hot encode

In [43]:
pipeline = Pipeline([
    ("imputer", DataFrameMaker(ColumnTransformer([
        ("num", SimpleImputer(), num_cols),
        ("cat", SimpleImputer(strategy="most_frequent", missing_values="Unknown"), cat_cols)
    ], remainder="passthrough"))),
    ("encoder", DataFrameMaker(ColumnTransformer([
        ("ordinal", OrdinalEncoder(), ["Gender", "HasTension", "AnyHeartDisease", "NeverMarried", "LivesIn"]),
        ("onehot", OneHotEncoder(), ["Occupation", "SmokingStatus"])
    ], remainder="passthrough"))),
    ("scaler", DataFrameMaker(ColumnTransformer([
        ("std", StandardScaler(), ["Age", "BMI"]),
        ("min-max", MinMaxScaler(), ["GlucoseLevel"])
    ], remainder="passthrough"))),
])
pipeline

Pipeline(steps=[('imputer',
                 DataFrameMaker(transformer=ColumnTransformer(remainder='passthrough',
                                                              transformers=[('num',
                                                                             SimpleImputer(),
                                                                             Index(['Age', 'GlucoseLevel', 'BMI'], dtype='object')),
                                                                            ('cat',
                                                                             SimpleImputer(missing_values='Unknown',
                                                                                           strategy='most_frequent'),
                                                                             Index(['Gender', 'HasTension', 'AnyHeartDisease', 'NeverMarried', 'Occupation',
       'LivesIn', 'Smoking...
                                                              transformers=[('ordinal',
                                                                             OrdinalEncoder(),
                                                                             ['Gender',
                                                                              'HasTension',
                                                                              'AnyHeartDisease',
                                                                              'NeverMarried',
                                                                              'LivesIn']),
                                                                            ('onehot',
                                                                             OneHotEncoder(),
                                                                             ['Occupation',
                                                                              'SmokingStatus'])]))),
                ('scaler',
                 DataFrameMaker(transformer=ColumnTransformer(remainder='passthrough',
                                                              transformers=[('std',
                                                                             StandardScaler(),
                                                                             ['Age',
                                                                              'BMI']),
                                                                            ('min-max',
                                                                             MinMaxScaler(),
                                                                             ['GlucoseLevel'])])))])

In [44]:
pipeline.fit_transform(X_train)

,Age,BMI,GlucoseLevel,Gender,HasTension,AnyHeartDisease,NeverMarried,LivesIn,Occupation_Govt_job,Occupation_Never_worked,Occupation_Private,Occupation_Self-employed,Occupation_children,SmokingStatus_formerly smoked,SmokingStatus_never smoked,SmokingStatus_smokes
2947,0.436336,0.284421,0.366568,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2234,-1.827889,-1.186687,0.511861,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2013,-1.150738,0.065045,0.464789,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2661,-0.798054,0.929643,0.349889,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2275,0.744934,-0.412420,0.364344,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2990,0.744934,-0.451133,0.322090,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2171,-0.489457,-0.515655,0.485915,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2578,0.965361,-1.147973,0.313566,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1328,-0.357201,0.232803,0.325056,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
546,-1.062567,-0.902789,0.297257,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [45]:
np.array(pipeline.transform(X_test)).mean()

0.2558055996337586

## Model Building

In [46]:
df = pd.read_csv("/kaggle/input/iitmbs-mlp-nppe2/T124OPPE2_ModelBuilding_V1.csv")
df.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation_Govt_job,Occupation_Never_worked,Occupation_Private,Occupation_Self-employed,Occupation_children,LivesIn,GlucoseLevel,BMI,SmokingStatus_formerly smoked,SmokingStatus_never smoked,SmokingStatus_smokes,HeartAttack
0,0.0,0.433901,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.203263,0.284421,0.0,1.0,0.0,0
1,1.0,-1.840435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.386014,-1.186687,0.0,1.0,0.0,0
2,1.0,-1.160260,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.326807,0.065045,0.0,1.0,0.0,0
3,1.0,-0.806002,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.182284,0.929643,0.0,1.0,0.0,0
4,0.0,0.743876,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.200466,-0.412420,0.0,0.0,1.0,1

The last column is the target column.

Last 30% rows of the dataset constitute test set and remaining rows form the training set.

Do not shuffle the dataset while splitting

You must have to use only training set to train all the estimator in questions below.

First row of the file has column names/ids, and it has no index column.

In [47]:
X = df.drop(columns="HeartAttack")
y = df["HeartAttack"].copy()

In [48]:
X_train = X.iloc[:-int(df.shape[0] * 0.3)]
y_train = y[:-int(df.shape[0] * 0.3)]

In [49]:
X_test = X.iloc[-int(df.shape[0] * 0.3):]
y_test = y[:-int(df.shape[0] * 0.3)]

In [50]:
X_train.shape, X_test.shape

((2800, 16), (1200, 16))

### Q2: Instantiate a perceptron classifier that with following parameters:

	random_state = 1729
	learning rate = 1
	Train for appropriate number of iterations
	Do not shuffle the dataset for each iteration.
	Include the intercept (bias) term.
	Use 10% of the data for validation fraction.
	Do not apply regularization.
	Set warm start to true.
Hint: one iteration of training indicates going over each sample exactly once.

Train the classifier on the training data.


Train the perceptron classifier for 5 iterations. What is value of bias (intercept) after 5th iteration?

In [51]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import precision_score

In [52]:
model = Perceptron(random_state=1729, eta0=1, max_iter=5, shuffle=False, validation_fraction=0.1, alpha=0)
model.fit(X_train, y_train)
print(model.intercept_)

[-3.]

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

In [53]:
precision_score(y_train, model.predict(X_train))

0.6666666666666666

### Q4: Train (on training data only) logistic regression using SGDClassifier. Use the following parameters:

	Choose appropriate loss value to obtain logistic regression
	penalty='l2',
	eta0=0.001,
	alpha=0,
	learning_rate='constant'
	random_state=1729.
	warm_start = True

Train the classifier for 5 iterations and note the value of the loss in each iteration. What will be the loss value after second iteration? Answer upto three decimal places.

Note: Set the remaining parameters, if any, accordingly to be able to get the loss value after second iteration. Also note that the classifier has to be trained for 5 iterations.

In [54]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import log_loss

In [55]:
model = SGDClassifier(loss="log_loss", penalty="l2", eta0=0.001, alpha=0, learning_rate="constant", random_state=1729, warm_start=True, max_iter=1)
for i in range(5):
    model.fit(X_train, y_train)
    print(log_loss(y_train, model.predict_proba(X_train)))

0.2529904609012919
0.20828682141739835
0.19406901833322654
0.18699850891012404
0.18255077295024025

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

# MLP Session 19a - OPPE 2 Revision by Parampreet Singh
## [Session video 🔗](https://youtu.be/9AlIXXQE86M)

- Concepts Revision from Week 1 to Week 10

# [Practice Set 1, 20+ Questions 🔗](https://www.kaggle.com/code/param302/session-13a-oppe-1-revision-2-by-parampreet/)
# [Practice Set 2, 30+ Questions 🔗](https://www.kaggle.com/param302/session-19b-oppe-2-revision-by-parampreet-singh)

### Mock OPPE 1 Solutions
- [Mock OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-1)
- [Mock OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitmbs-mlp-oppe-1-mock-2)

### NPPE 1 Solutions
- [NPPE OPPE 1a 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part1)
- [NPPE OPPE 1b 🔗](https://www.kaggle.com/code/param302/iitm-mlp-nppe1-part2)

#### [Session Playlist 🔗](https://www.youtube.com/playlist?list=PLClULgPbRPsA1twUfMlWkI4yJeqjsSi23)